name: ynov_immo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  badges: ^1.1.6
  carousel_slider: ^3.0.0
  flutter_map: any
  http: '>=0.11.1 <0.12.0'
  flutter_web: any
  flutter_web_ui: any
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  smooth_star_rating: ^1.0.4

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
