name: ynov_immo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: '^0.12.0'
  date_time_picker: "^1.1.1"
  time_picker_widget: ^1.0.0+9
  table_calendar: ^2.0.1
  flutter:
    sdk: flutter

  time_range: ^0.5.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.2+1
  smooth_star_rating: ^1.0.4

dependency_overrides:
  intl: ^0.16.0

dev_dependencies:
  build_runner: ^1.5.0
  pedantic: ^1.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

